# Dependencies
highligher:       pygments
#redcarpet:
  #extensions: ['smart']

# Permalinks
permalink:        pretty

# Setup
title:            Git@Me
tagline:          'Discover great open source projects'
description:      'exploring open source'
url:              http://gitat.me
baseurl:          /
fbc-comments-firebase: https://gitat-me.firebaseio.com/

author:
  name:           'Neal Shyam'
  url:            https://twitter.com/nealrs


gems: [jekyll-paginate]
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nealrs/gitatme-comments/

demo:             http://gam.s3.amazonaws.com/demo/
img:              http://gam.s3.amazonaws.com/img/
aws:              http://gam.s3.amazonaws.com/

timezone:         America/New_York
TZ:               America/New_York
future: true
